/**
 * SAL Education - College Attendance Management System
 * Manage Students Page
 * 
 * Complete CRUD for student management with class and batch assignment.
 * Features:
 * - Add/Edit/Delete students
 * - Assign to class and batch
 * - Filter by class/batch
 * - Search functionality
 * 
 * VIVA NOTE: Students are linked to both class (for theory) and
 * batch (for lab sessions). This is a many-to-one relationship.
 */

import { useState, useEffect } from 'react';
import { toast } from 'react-toastify';
import { Card, Button, Table, Modal, Input, Select, ConfirmDialog, DataImportCard } from '../../components';
import { studentService, classService, batchService } from '../../services/dataService';
import { importConfigs } from '../../constants/importConfigs';

const ManageStudents = () => {
  const getDefaultPassword = (enrollmentNo) => {
    if (!enrollmentNo) return '';
    return enrollmentNo.length >= 6
      ? enrollmentNo
      : `${enrollmentNo}${'123456'.slice(enrollmentNo.length)}`;
  };

  // State management
  const [students, setStudents] = useState([]);
  const [classes, setClasses] = useState([]);
  const [batches, setBatches] = useState([]);
  const [filteredBatches, setFilteredBatches] = useState([]);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [deleteDialog, setDeleteDialog] = useState({ isOpen: false, item: null });
  const [editingId, setEditingId] = useState(null);
  const [credentialsPopup, setCredentialsPopup] = useState({
    isOpen: false,
    name: '',
    username: '',
    password: '',
    enrollmentNo: '',
    isAutoGenerated: true
  });
  
  // Form state
  const [formData, setFormData] = useState({
    enrollmentNo: '',
    name: '',
    email: '',
    phone: '',
    classId: '',
    batchId: ''
  });
  
  // Filter state
  const [filters, setFilters] = useState({
    classId: '',
    searchTerm: ''
  });

  /**
   * Load initial data
   */
  useEffect(() => {
    loadData();
  }, []);

  /**
   * Update filtered batches when class changes in form
   */
  useEffect(() => {
    const loadBatches = async () => {
      if (formData.classId) {
        const classBatches = await batchService.getByClassId(formData.classId);
        setFilteredBatches(classBatches);
      } else {
        setFilteredBatches([]);
      }
    };
    loadBatches();
  }, [formData.classId]);

  const loadData = async () => {
    const [studentsData, classesData, batchesData] = await Promise.all([
      studentService.getAll(),
      classService.getAll(),
      batchService.getAll()
    ]);
    // Enrich students with class and batch names
    const enrichedStudents = studentsData.map(student => ({
      ...student,
      className: classesData.find(c => c.id === student.classId)?.name || 'N/A',
      batchName: batchesData.find(b => b.id === student.batchId)?.name || 'N/A'
    }));
    setStudents(enrichedStudents);
    setClasses(classesData);
    setBatches(batchesData);
  };

  const handleInputChange = (e) => {
    const { id, value } = e.target;
    setFormData(prev => ({ ...prev, [id]: value }));
    
    // Reset batch when class changes
    if (id === 'classId') {
      setFormData(prev => ({ ...prev, batchId: '' }));
    }
  };

  const handleAdd = () => {
    setFormData({
      enrollmentNo: '',
      name: '',
      email: '',
      phone: '',
      classId: '',
      batchId: ''
    });
    setEditingId(null);
    setIsModalOpen(true);
  };

  const handleEdit = (student) => {
    setFormData({
      enrollmentNo: student.enrollmentNo,
      name: student.name,
      email: student.email,
      phone: student.phone,
      classId: student.classId.toString(),
      batchId: student.batchId ? student.batchId.toString() : ''
    });
    setEditingId(student.id);
    setIsModalOpen(true);
  };

  const handleDeleteClick = (student) => {
    setDeleteDialog({ isOpen: true, item: student });
  };

  const handleDeleteConfirm = async () => {
    if (deleteDialog.item) {
      try {
        await studentService.delete(deleteDialog.item.id);
        await loadData();
        toast.success('Student deleted successfully!');
      } catch (error) {
        toast.error(error.response?.data?.message || 'Failed to delete student.');
      }
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    // Validation
    if (!formData.enrollmentNo || !formData.name || !formData.email || !formData.classId) {
      toast.error('Please fill in all required fields');
      return;
    }

    // Email validation
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(formData.email)) {
      toast.error('Please enter a valid email address');
      return;
    }

    try {
      if (editingId) {
        await studentService.update(editingId, formData);
        toast.success('Student updated successfully!');
      } else {
        const createdStudent = await studentService.create(formData);
        const credentials = createdStudent?.credentials || {
          username: formData.email,
          password: getDefaultPassword(formData.enrollmentNo),
          isAutoGenerated: true
        };

        toast.success('Student added successfully!');
        setCredentialsPopup({
          isOpen: true,
          name: formData.name,
          username: credentials.username,
          password: credentials.password,
          enrollmentNo: formData.enrollmentNo,
          isAutoGenerated: credentials.isAutoGenerated
        });
      }

      setIsModalOpen(false);
      await loadData();
    } catch (error) {
      toast.error(error.response?.data?.message || 'Operation failed. Please try again.');
    }
  };

  // Class options
  const classOptions = classes.map(c => ({
    value: c.id.toString(),
    label: `${c.name} - ${c.department}`
  }));

  // Batch options based on selected class
  const batchOptions = filteredBatches.map(b => ({
    value: b.id.toString(),
    label: b.name
  }));

  // Apply filters
  let displayStudents = students;
  if (filters.classId) {
    displayStudents = displayStudents.filter(s => s.classId === parseInt(filters.classId));
  }
  if (filters.searchTerm) {
    const term = filters.searchTerm.toLowerCase();
    displayStudents = displayStudents.filter(s =>
      s.name.toLowerCase().includes(term) ||
      s.enrollmentNo.toLowerCase().includes(term) ||
      s.email.toLowerCase().includes(term)
    );
  }

  // Table columns
  const columns = [
    { key: 'enrollmentNo', label: 'Enrollment No' },
    { key: 'name', label: 'Student Name' },
    { key: 'email', label: 'Email' },
    { key: 'phone', label: 'Phone' },
    { key: 'className', label: 'Class' },
    { key: 'batchName', label: 'Batch' }
  ];

  return (
    <div className="space-y-6">
      {/* Page header */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="text-2xl font-bold text-gray-800">Manage Students</h1>
          <p className="text-gray-600">Add, edit, and manage student records</p>
        </div>
        <Button onClick={handleAdd}>
          <span className="flex items-center">
            <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M18 9v3m0 0v3m0-3h3m-3 0h-3m-2-5a4 4 0 11-8 0 4 4 0 018 0zM3 20a6 6 0 0112 0v1H3v-1z" />
            </svg>
            Add Student
          </span>
        </Button>
      </div>

      <DataImportCard
        config={importConfigs.students}
        onImported={loadData}
      />

      {/* Filters */}
      <Card>
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          <Input
            id="searchTerm"
            placeholder="Search by name, enrollment, or email..."
            value={filters.searchTerm}
            onChange={(e) => setFilters(prev => ({ ...prev, searchTerm: e.target.value }))}
          />
          <Select
            id="filterClass"
            value={filters.classId}
            onChange={(e) => setFilters(prev => ({ ...prev, classId: e.target.value }))}
            options={classOptions}
            placeholder="All Classes"
          />
          <div className="text-sm text-gray-500 flex items-center justify-end">
            Showing {displayStudents.length} of {students.length} students
          </div>
        </div>
      </Card>

      {/* Students table */}
      <Card>
        <Table
          columns={columns}
          data={displayStudents}
          onEdit={handleEdit}
          onDelete={handleDeleteClick}
          emptyMessage="No students found. Click 'Add Student' to create one."
        />
      </Card>

      {/* Add/Edit Modal */}
      <Modal
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        title={editingId ? 'Edit Student' : 'Add New Student'}
        size="lg"
      >
        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <Input
              label="Enrollment Number"
              id="enrollmentNo"
              value={formData.enrollmentNo}
              onChange={handleInputChange}
              placeholder="e.g., SAL2024001"
              required
              disabled={!!editingId}
            />
            <Input
              label="Full Name"
              id="name"
              value={formData.name}
              onChange={handleInputChange}
              placeholder="Enter full name"
              required
            />
            <Input
              label="Email"
              id="email"
              type="email"
              value={formData.email}
              onChange={handleInputChange}
              placeholder="student@sal.edu"
              required
            />
            <Input
              label="Phone Number"
              id="phone"
              value={formData.phone}
              onChange={handleInputChange}
              placeholder="Enter phone number"
            />
            <Select
              label="Class"
              id="classId"
              value={formData.classId}
              onChange={handleInputChange}
              options={classOptions}
              placeholder="Select class"
              required
            />
            <Select
              label="Batch (for Labs)"
              id="batchId"
              value={formData.batchId}
              onChange={handleInputChange}
              options={batchOptions}
              placeholder="Select batch"
              disabled={!formData.classId}
            />
          </div>

          <div className="flex justify-end space-x-3 pt-4">
            <Button variant="outline" onClick={() => setIsModalOpen(false)}>
              Cancel
            </Button>
            <Button type="submit">
              {editingId ? 'Update Student' : 'Add Student'}
            </Button>
          </div>
        </form>
      </Modal>

      {/* Delete Confirmation */}
      <ConfirmDialog
        isOpen={deleteDialog.isOpen}
        onClose={() => setDeleteDialog({ isOpen: false, item: null })}
        onConfirm={handleDeleteConfirm}
        title="Delete Student"
        message={`Are you sure you want to delete "${deleteDialog.item?.name}"? This will also remove their attendance records.`}
        confirmText="Delete"
        variant="danger"
      />

      <Modal
        isOpen={credentialsPopup.isOpen}
        onClose={() =>
          setCredentialsPopup({
            isOpen: false,
            name: '',
            username: '',
            password: '',
            enrollmentNo: '',
            isAutoGenerated: true
          })
        }
        title="Student Login Credentials"
        size="md"
      >
        <div className="space-y-3">
          <p className="text-sm text-gray-700">
            Save these credentials for <span className="font-semibold">{credentialsPopup.name}</span>.
          </p>
          <div className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-xs text-amber-900">
            These credentials are shown only once.
          </div>
          <div className="space-y-2 rounded-lg border border-gray-200 bg-gray-50 p-3 text-sm">
            <p><span className="font-medium">Enrollment No:</span> {credentialsPopup.enrollmentNo}</p>
            <p><span className="font-medium">Username:</span> {credentialsPopup.username}</p>
            <p><span className="font-medium">Password:</span> {credentialsPopup.password}</p>
            <p><span className="font-medium">Password Type:</span> {credentialsPopup.isAutoGenerated ? 'Auto-generated default' : 'Custom provided'}</p>
          </div>
          <div className="flex justify-end pt-2">
            <Button
              onClick={() =>
                setCredentialsPopup({
                  isOpen: false,
                  name: '',
                  username: '',
                  password: '',
                  enrollmentNo: '',
                  isAutoGenerated: true
                })
              }
            >
              Done
            </Button>
          </div>
        </div>
      </Modal>
    </div>
  );
};

export default ManageStudents;
