/**
 * SAL Education - College Attendance Management System
 * Manage Teachers/Faculty Page
 * 
 * Complete CRUD for faculty management.
 * Teachers can be assigned to theory and lab subjects.
 * 
 * VIVA NOTE: Teachers have a many-to-many relationship with subjects.
 * A teacher can teach theory for one subject and lab for another.
 */

import { useState, useEffect } from 'react';
import { toast } from 'react-toastify';
import { Card, Button, Table, Modal, Input, Select, ConfirmDialog, DataImportCard } from '../../components';
import { teacherService, subjectService } from '../../services/dataService';
import { importConfigs } from '../../constants/importConfigs';
import { TEACHER_PRIORITY_OPTIONS, formatTeacherPriority } from '../../constants/roles';
import { getTeacherDepartments, formatTeacherDepartments } from '../../utils/teacherDepartments';

const ManageTeachers = () => {
  const getDefaultPassword = (employeeId) => {
    if (!employeeId) return '';
    return employeeId.length >= 6
      ? employeeId
      : `${employeeId}${'123456'.slice(employeeId.length)}`;
  };

  const subjectHasTeacher = (subject, teacherId) => {
    const assignedTeacherIds = [...new Set([
      ...(Array.isArray(subject?.theoryFacultyIds) ? subject.theoryFacultyIds : []),
      ...(Array.isArray(subject?.labFacultyIds) ? subject.labFacultyIds : []),
      subject?.theoryFacultyId,
      subject?.labFacultyId
    ].filter(Boolean).map(id => Number(id)))];

    return assignedTeacherIds.includes(Number(teacherId));
  };

  // State
  const [teachers, setTeachers] = useState([]);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [deleteDialog, setDeleteDialog] = useState({ isOpen: false, item: null });
  const [editingId, setEditingId] = useState(null);
  const [searchTerm, setSearchTerm] = useState('');
  const [credentialsPopup, setCredentialsPopup] = useState({
    isOpen: false,
    name: '',
    username: '',
    password: '',
    employeeId: '',
    isAutoGenerated: true
  });

  // Form state
  const [formData, setFormData] = useState({
    employeeId: '',
    name: '',
    email: '',
    phone: '',
    departments: [],
    qualification: '',
    priority: 'FACULTY'
  });

  // Department options
  const departmentOptions = [
    { value: 'Computer Engineering', label: 'Computer Engineering' },
    { value: 'Information Technology', label: 'Information Technology' },
    { value: 'Electronics Engineering', label: 'Electronics Engineering' },
    { value: 'Mechanical Engineering', label: 'Mechanical Engineering' },
    { value: 'Civil Engineering', label: 'Civil Engineering' },
    { value: 'Science & Humanities', label: 'Science & Humanities' },
  ];

  // Role/Priority options
  useEffect(() => {
    loadData();
  }, []);

  const loadData = async () => {
    const [teacherData, subjectsData] = await Promise.all([
      teacherService.getAll(),
      subjectService.getAll()
    ]);
    // Enrich with assigned subjects count
    const enrichedTeachers = teacherData.map(teacher => ({
      ...teacher,
      subjectsCount: subjectsData.filter(
        subject => subjectHasTeacher(subject, teacher.id)
      ).length
    }));
    setTeachers(enrichedTeachers);
  };

  const handleInputChange = (e) => {
    const { id, value } = e.target;
    setFormData(prev => ({ ...prev, [id]: value }));
  };

  const handleAdd = () => {
    setFormData({
      employeeId: '',
      name: '',
      email: '',
      phone: '',
      departments: [],
      qualification: '',
      priority: 'FACULTY'
    });
    setEditingId(null);
    setIsModalOpen(true);
  };

  const handleEdit = (teacher) => {
    setFormData({
      employeeId: teacher.employeeId,
      name: teacher.name,
      email: teacher.email,
      phone: teacher.phone,
      departments: getTeacherDepartments(teacher),
      qualification: teacher.qualification || '',
      priority: teacher.priority || 'FACULTY'
    });
    setEditingId(teacher.id);
    setIsModalOpen(true);
  };

  const handleDeleteClick = (teacher) => {
    setDeleteDialog({ isOpen: true, item: teacher });
  };

  const handleDeleteConfirm = async () => {
    if (deleteDialog.item) {
      await teacherService.delete(deleteDialog.item.id);
      await loadData();
      toast.success('Teacher deleted successfully!');
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    if (!formData.employeeId || !formData.name || !formData.email || formData.departments.length === 0) {
      toast.error('Please fill in all required fields');
      return;
    }

    // Email validation
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(formData.email)) {
      toast.error('Please enter a valid email address');
      return;
    }

    try {
      const payload = {
        ...formData,
        departments: formData.departments
      };

      if (editingId) {
        await teacherService.update(editingId, payload);
        toast.success('Teacher updated successfully!');
      } else {
        const createdTeacher = await teacherService.create(payload);
        const credentials = createdTeacher?.credentials || {
          username: payload.email,
          password: getDefaultPassword(payload.employeeId),
          isAutoGenerated: true
        };

        toast.success('Teacher added successfully!');
        setCredentialsPopup({
          isOpen: true,
          name: payload.name,
          username: credentials.username,
          password: credentials.password,
          employeeId: payload.employeeId,
          isAutoGenerated: credentials.isAutoGenerated
        });
      }

      setIsModalOpen(false);
      await loadData();
    } catch (error) {
      toast.error(error.response?.data?.message || 'Operation failed. Please try again.');
    }
  };

  // Filter teachers
  const filteredTeachers = teachers.filter(t =>
    t.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
    t.employeeId.toLowerCase().includes(searchTerm.toLowerCase()) ||
    formatTeacherDepartments(t).toLowerCase().includes(searchTerm.toLowerCase())
  );

  const toggleDepartmentSelection = (departmentValue) => {
    setFormData((prev) => ({
      ...prev,
      departments: prev.departments.includes(departmentValue)
        ? prev.departments.filter((department) => department !== departmentValue)
        : [...prev.departments, departmentValue]
    }));
  };

  // Priority badge colors
  const priorityColors = {
    ADMIN: 'bg-red-100 text-red-800',
    PRINCIPAL: 'bg-purple-100 text-purple-800',
    HOD: 'bg-orange-100 text-orange-800',
    CLASS_COORDINATOR: 'bg-teal-100 text-teal-800',
    FACULTY: 'bg-gray-100 text-gray-800',
  };

  // Table columns
  const columns = [
    { key: 'employeeId', label: 'Employee ID' },
    { key: 'name', label: 'Name' },
    {
      key: 'priority',
      label: 'Role',
      render: (value) => (
        <span className={`px-2 py-1 rounded-full text-xs font-medium ${priorityColors[value] || priorityColors.FACULTY}`}>
          {formatTeacherPriority(value || 'FACULTY')}
        </span>
      )
    },
    { key: 'email', label: 'Email' },
    {
      key: 'departments',
      label: 'Departments',
      render: (_, row) => {
        const departments = getTeacherDepartments(row);

        return (
          <div className="max-w-xs whitespace-normal">
            {departments.length > 0 ? (
              <div className="flex flex-wrap gap-1">
                {departments.map((department) => (
                  <span
                    key={`${row.id}-${department}`}
                    className="rounded-full bg-emerald-100 px-2 py-1 text-xs font-medium text-emerald-800"
                  >
                    {department}
                  </span>
                ))}
              </div>
            ) : 'Unassigned'}
          </div>
        );
      }
    },
    { key: 'qualification', label: 'Qualification' },
    {
      key: 'subjectsCount',
      label: 'Subjects',
      render: (value) => (
        <span className="px-2 py-1 bg-blue-100 text-blue-800 rounded-full text-xs font-medium">
          {value} subjects
        </span>
      )
    }
  ];

  return (
    <div className="space-y-6">
      {/* Page header */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="text-2xl font-bold text-gray-800">Manage Teachers</h1>
          <p className="text-gray-600">Add, edit, and manage faculty members</p>
        </div>
        <Button onClick={handleAdd}>
          <span className="flex items-center">
            <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M18 9v3m0 0v3m0-3h3m-3 0h-3m-2-5a4 4 0 11-8 0 4 4 0 018 0zM3 20a6 6 0 0112 0v1H3v-1z" />
            </svg>
            Add Teacher
          </span>
        </Button>
      </div>

      <DataImportCard
        config={importConfigs.teachers}
        onImported={loadData}
      />

      {/* Search */}
      <Card>
        <div className="flex flex-col sm:flex-row gap-4">
          <div className="flex-1">
            <Input
              id="search"
              placeholder="Search by name, ID, or department..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
            />
          </div>
          <div className="text-sm text-gray-500 flex items-center">
            Total: {filteredTeachers.length} teachers
          </div>
        </div>
      </Card>

      {/* Teachers table */}
      <Card>
        <Table
          columns={columns}
          data={filteredTeachers}
          onEdit={handleEdit}
          onDelete={handleDeleteClick}
          emptyMessage="No teachers found. Click 'Add Teacher' to create one."
        />
      </Card>

      {/* Add/Edit Modal */}
      <Modal
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        title={editingId ? 'Edit Teacher' : 'Add New Teacher'}
        size="lg"
      >
        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <Input
              label="Employee ID"
              id="employeeId"
              value={formData.employeeId}
              onChange={handleInputChange}
              placeholder="e.g., SAL-T001"
              required
              disabled={!!editingId}
            />
            <Input
              label="Full Name"
              id="name"
              value={formData.name}
              onChange={handleInputChange}
              placeholder="e.g., Prof. John Smith"
              required
            />
            <Input
              label="Email"
              id="email"
              type="email"
              value={formData.email}
              onChange={handleInputChange}
              placeholder="teacher@sal.edu"
              required
            />
            <Input
              label="Phone Number"
              id="phone"
              value={formData.phone}
              onChange={handleInputChange}
              placeholder="Enter phone number"
            />
            <Select
              label="Role / Priority"
              id="priority"
              value={formData.priority}
              onChange={handleInputChange}
              options={TEACHER_PRIORITY_OPTIONS}
              placeholder="Select role"
            />
            <Input
              label="Qualification"
              id="qualification"
              value={formData.qualification}
              onChange={handleInputChange}
              placeholder="e.g., M.Tech, PhD"
            />
            <div className="md:col-span-2">
              <label className="mb-1 block text-sm font-medium text-gray-700">
                Departments <span className="text-red-500">*</span>
              </label>
              <div className="grid grid-cols-1 gap-2 rounded-lg border border-gray-300 p-3 sm:grid-cols-2">
                {departmentOptions.map((option) => {
                  const isSelected = formData.departments.includes(option.value);

                  return (
                    <label
                      key={option.value}
                      className={`flex cursor-pointer items-center gap-3 rounded-lg border p-3 transition-colors ${
                        isSelected
                          ? 'border-emerald-300 bg-emerald-50'
                          : 'border-transparent hover:bg-gray-50'
                      }`}
                    >
                      <input
                        type="checkbox"
                        checked={isSelected}
                        onChange={() => toggleDepartmentSelection(option.value)}
                        className="h-4 w-4 rounded border-gray-300 text-emerald-600 focus:ring-emerald-500"
                      />
                      <span className="text-sm text-gray-800">{option.label}</span>
                    </label>
                  );
                })}
              </div>
              <p className="mt-1 text-xs text-gray-500">
                {formData.departments.length > 0
                  ? `${formData.departments.length} department${formData.departments.length > 1 ? 's' : ''} selected`
                  : 'No department selected'}
              </p>
            </div>
          </div>

          <div className="flex justify-end space-x-3 pt-4">
            <Button variant="outline" onClick={() => setIsModalOpen(false)}>
              Cancel
            </Button>
            <Button type="submit">
              {editingId ? 'Update Teacher' : 'Add Teacher'}
            </Button>
          </div>
        </form>
      </Modal>

      {/* Delete Confirmation */}
      <ConfirmDialog
        isOpen={deleteDialog.isOpen}
        onClose={() => setDeleteDialog({ isOpen: false, item: null })}
        onConfirm={handleDeleteConfirm}
        title="Delete Teacher"
        message={`Are you sure you want to delete "${deleteDialog.item?.name}"? This will also unassign them from all subjects.`}
        confirmText="Delete"
        variant="danger"
      />

      <Modal
        isOpen={credentialsPopup.isOpen}
        onClose={() =>
          setCredentialsPopup({
            isOpen: false,
            name: '',
            username: '',
            password: '',
            employeeId: '',
            isAutoGenerated: true
          })
        }
        title="Teacher Login Credentials"
        size="md"
      >
        <div className="space-y-3">
          <p className="text-sm text-gray-700">
            Save these credentials for <span className="font-semibold">{credentialsPopup.name}</span>.
          </p>
          <div className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-xs text-amber-900">
            These credentials are shown only once.
          </div>
          <div className="space-y-2 rounded-lg border border-gray-200 bg-gray-50 p-3 text-sm">
            <p><span className="font-medium">Employee ID:</span> {credentialsPopup.employeeId}</p>
            <p><span className="font-medium">Username:</span> {credentialsPopup.username}</p>
            <p><span className="font-medium">Password:</span> {credentialsPopup.password}</p>
            <p><span className="font-medium">Password Type:</span> {credentialsPopup.isAutoGenerated ? 'Auto-generated default' : 'Custom provided'}</p>
          </div>
          <div className="flex justify-end pt-2">
            <Button
              onClick={() =>
                setCredentialsPopup({
                  isOpen: false,
                  name: '',
                  username: '',
                  password: '',
                  employeeId: '',
                  isAutoGenerated: true
                })
              }
            >
              Done
            </Button>
          </div>
        </div>
      </Modal>
    </div>
  );
};

export default ManageTeachers;
